source: "./source" # directory path or name of the file to be processed
destination: "./generated"

attributes:
  showtitle: ''
  stylesheet: 'foundation.css'
  stylesdir: 'css'
  nofooter: 'yes'
  icons: 'font'

options:
  doctype: 'article'
  to_dir: 'generated'
  safe: 'unsafe'

http:
  port: 3000
  address: 0.0.0.0

pdf:
  format: A4
  orientation: portrait
  zoomFactor: "0.55"
  border:
    top: 20px
    right: 15px
    bottom: 20px
    left: 15px
