source: "./source" # directory path or name of the file to be processed
destination: "./generated"

attributes:
  backend: 'revealjs'
  icons: font
  revealjs_theme: white
  revealjs_transition: none
  revealjs_history: true
  revealjs_center: false

options:
  to_dir: './generated'
  safe: 'unsafe'

http:
  port: 3000
  address: 0.0.0.0
